/**
 * Selectable periods, and the periods that do not exist.
 *
 * ── Why this is not a date picker ──────────────────────────────────────────
 *
 * A free date range would let an operator select May to December 2025 and read
 * a report. There is no identity in those months — the Payment Account
 * Reference across the whole estate was 14 to 37 distinct values per month
 * against 13 to 18 million transactions — so the report would be a picture of
 * nobody, drawn confidently. Ninety days was never a product decision; it was
 * the length of the only unbroken run of trustworthy months.
 *
 * So the control **grades rather than filters**. Every window a reasonable
 * person might ask for — a single month, an unbroken run, the last 3, 6 or 12
 * months — is offered, and each one either resolves or names the months that
 * stopped it. That second half is the more useful one: a merchant who can see
 * "May–Dec 2025 · no card capture" has something to escalate, where a greyed-out
 * calendar reads as a product limitation and gets escalated at us instead.
 *
 * The offer list is generated by `candidateWindows` in `scripts/grade.ts`, which
 * the extract and `npm run periods` both call, so what is offered cannot drift
 * from what is buildable.
 *
 * ── Two clocks, kept apart ─────────────────────────────────────────────────
 *
 * Card capture caps the card tier at three months at Coffee Guru. The loyalty
 * scan never failed and reaches back twenty-one, so a **member window** is the
 * only way a twelve-month question gets an answer here. It is not the same
 * report over more months: it joins no payments, so it sees scanned trade only
 * and its population is smaller. Member windows carry `kind: "member"` and an
 * `m-` id prefix — without the prefix they would share a route segment with the
 * card window over the same months, and serve one population to a reader who
 * asked for the other.
 *
 * The period is a route segment rather than a filter, because it changes every
 * figure on the page and because it keeps the whole build statically generated —
 * which is what lets this deploy with no environment variable, no key and no
 * runtime call.
 */
import type { ClaimLevel } from "./types";
export type { PeriodCandidate, PeriodGroup, PeriodKind } from "../../scripts/grade";
import type { PeriodCandidate, PeriodGroup, PeriodKind } from "../../scripts/grade";

export type Period = {
  /** `2026-05_2026-07`, or `m-2025-08_2026-07` for a member window. */
  id: string;
  start: string;
  end: string;
  months: number;
  claim: ClaimLevel;
  /**
   * Which identity spine the window is measured on. **Optional for a reason:**
   * a snapshot extracted before member windows existed carries no `kind`, and
   * every one of those is a card window. Absent reads as `"card"` rather than
   * the app guessing or refusing.
   */
  kind?: PeriodKind;
  /** Human label. Absent on older snapshots, where it is derived from the dates. */
  label?: string;
  group?: PeriodGroup;
};

export type PeriodGap = {
  start: string;
  end: string;
  months: number;
  reason: string;
};

export type Periods = {
  slug: string;
  name: string;
  /**
   * The windows a snapshot exists for, most recent first. The first entry is
   * what the product opens on.
   *
   * This is still the list the router generates from, so it is still *only* the
   * extracted windows — a candidate the extract skipped is not routable and
   * must not appear here.
   */
  periods: Period[];
  /**
   * Everything an operator might ask for, extracted or not.
   *
   * Absent on a snapshot written before the window set was generated, in which
   * case the control falls back to `periods` and behaves exactly as it did.
   */
  candidates?: PeriodCandidate[];
  gaps: PeriodGap[];
  monthsTested: number;
  monthsUsable: number;
  gradedAt: string;
};

/**
 * Plain English for a grading verdict, for the reader who has to act on it.
 *
 * The grading's own vocabulary is precise and useless to an operator: "one token
 * dominates" describes the test, not the consequence. These describe the
 * consequence, and each one names who can do something about it.
 */
export const GAP_EXPLANATION: Record<string, { what: string; who: string }> = {
  "not trading": {
    what: "The venue had not opened yet. Not a data problem.",
    who: "Nobody — this is a business fact and it is here so it is not counted as a failure.",
  },
  "payments incomplete": {
    what: "The card feed carried a fraction of the month's transactions while the tills recorded a normal month.",
    who: "Platform — the acquirer feed, not the venue.",
  },
  "no card capture": {
    what: "Card references were absent estate-wide, so no payment can be attached to a person.",
    who: "Platform — CI-028. This is the May–December 2025 blackout.",
  },
  "one token dominates": {
    what: "References were present but one value covered a tenth or more of the month's card volume, so they do not identify individual cards.",
    who: "Platform — CI-028.",
  },
  "degraded card capture": {
    what: "The same handful of references repeated across the month rather than one per card.",
    who: "Platform — CI-028.",
  },
  "card capture partial": {
    what: "References were genuine but too few transactions carried one to recover a population.",
    who: "Platform — CI-028. Recovering coverage here would open the period.",
  },
};

export function explainGap(reason: string): { what: string; who: string } {
  return (
    GAP_EXPLANATION[reason] ?? {
      what: "This period did not pass the card-capture grading.",
      who: "Platform.",
    }
  );
}

/** The period a URL names, or the default. Never throws on a stale link. */
export function resolvePeriod(all: Periods, id: string | undefined): Period {
  return all.periods.find((p) => p.id === id) ?? all.periods[0];
}

/**
 * Which spine a period runs on, with the absent case named rather than guessed.
 *
 * Every window written before member windows existed is a card window, so the
 * default is not a fallback — it is the correct answer for the entire back
 * catalogue.
 */
export function spineOf(p: Period): PeriodKind {
  return p.kind ?? "card";
}

/**
 * The control's contents: every candidate, grouped, with the extracted ones
 * marked selectable.
 *
 * **A candidate that grades cleanly but has no snapshot is not selectable**, and
 * that is a different sentence from "your data does not support it" — one is a
 * build that has not run, the other is a payment feed that failed. The control
 * keeps them apart because only the second is something an operator can act on.
 */
export type PickerRow = PeriodCandidate & {
  /** A snapshot exists and the route resolves. */
  selectable: boolean;
  /** Why it is not selectable. Null when it is. */
  unavailable: "not-graded" | "not-extracted" | null;
};

export function pickerRows(all: Periods): { group: PeriodGroup; title: string; rows: PickerRow[] }[] {
  const extracted = new Set(all.periods.map((p) => p.id));
  const candidates: PeriodCandidate[] =
    all.candidates ??
    // The pre-generation shape: the extracted runs, and nothing else offered.
    all.periods.map((p) => ({
      id: p.id,
      label: p.label ?? `${p.start.slice(0, 7)} – ${p.end.slice(0, 7)}`,
      aliases: [],
      group: "run" as PeriodGroup,
      kind: "card" as PeriodKind,
      start: p.start,
      end: p.end,
      months: p.months,
      claim: p.claim,
      gradable: true,
      failing: [],
    }));

  const rows: PickerRow[] = candidates.map((c) => {
    const selectable = c.gradable && extracted.has(c.id);
    return {
      ...c,
      selectable,
      unavailable: selectable ? null : !c.gradable ? "not-graded" : "not-extracted",
    };
  });

  const TITLES: { group: PeriodGroup; title: string }[] = [
    { group: "run", title: "Unbroken runs" },
    { group: "rolling", title: "Rolling" },
    { group: "month", title: "One month" },
    { group: "member", title: "Members only — the loyalty scan" },
  ];
  return TITLES
    .map(({ group, title }) => ({ group, title, rows: rows.filter((r) => r.group === group) }))
    .filter((g) => g.rows.length > 0);
}

/**
 * How far apart two periods are, in months, for the comparison affordance.
 *
 * Returns null where the two do not sit a whole number of months apart, which
 * cannot happen with month-aligned runs but keeps the caller honest.
 */
export function monthsApart(a: Period, b: Period): number {
  const d = (s: string) => new Date(`${s}T00:00:00Z`);
  return (
    (d(b.start).getUTCFullYear() - d(a.start).getUTCFullYear()) * 12 +
    (d(b.start).getUTCMonth() - d(a.start).getUTCMonth())
  );
}

/**
 * Whether two periods are twelve months apart, and therefore comparable
 * year-on-year.
 *
 * Published because it is almost always false here, and the reason it is false
 * is the finding: the 2025 blackout sits exactly where the comparison months
 * would be.
 */
export function isYearOnYear(a: Period, b: Period): boolean {
  return Math.abs(monthsApart(a, b)) === 12;
}

/**
 * The previous readable period, and how far away it actually is.
 *
 * ── This is the whole reason "vs previous period" is not a free column ─────
 *
 * `periods` is one entry per unbroken run of trustworthy card months, newest
 * first. **Consecutive entries are not consecutive quarters.** At Coffee Guru
 * the current window opens May 2026 and the previous readable run ends April
 * 2025 — thirteen months earlier, because every month between them failed card
 * capture and is not in the snapshot at all.
 *
 * A change column computed across that and labelled "previous period" is a lie
 * of exactly the kind this build exists to refuse: it reads as one quarter of
 * movement and it is a year of it, most of which happened where nothing was
 * measured. So the gap comes back with the period and every surface that draws
 * a comparison is obliged to state it.
 *
 * Returns null where there is no earlier run, which is the Meat Flour Wine case
 * — one period, and therefore no comparison offered rather than an empty one.
 */
export function previousReadable(
  all: Periods,
  id: string,
): { period: Period; gapMonths: number; label: string; adjacent: boolean } | null {
  const i = all.periods.findIndex((p) => p.id === id);
  if (i < 0) return null;
  const current = all.periods[i];
  // Newest first, so the next entry along is the previous run.
  const prev = all.periods[i + 1];
  if (!prev) return null;

  /**
   * ── The gap is the months that are missing, not the months between the
   *    two calendar labels (C-6) ─────────────────────────────────────────────
   *
   * This counted from the *month containing* `prev.end` to the month containing
   * `current.start`, which is one more than the number of months actually
   * absent. A run ending 30 April 2025 against a window opening 1 May 2026
   * reported **13 months** when the missing months are May 2025 to April 2026 —
   * **12**. The figure appears on the face of the segment grid and inside the
   * density-change explanation, so it was wrong in two places at once.
   *
   * Counting the absent months directly also makes the adjacency test read as
   * what it means: zero missing months is a true previous period.
   */
  const d = (s: string) => new Date(`${s}T00:00:00Z`);
  const monthsBetween =
    (d(current.start).getUTCFullYear() - d(prev.end).getUTCFullYear()) * 12 +
    (d(current.start).getUTCMonth() - d(prev.end).getUTCMonth());
  const gapMonths = Math.max(0, monthsBetween - 1);

  return {
    period: prev,
    gapMonths,
    label: `${monthName(prev.start)} – ${monthName(prev.end)}`,
    // No missing months at all is a true previous period.
    adjacent: gapMonths === 0,
  };
}

function monthName(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-AU", {
    month: "short", year: "numeric", timeZone: "UTC",
  });
}
